--- 
title: "生物信息学项目驱动实战"
author: "<a href='https://github.com/lemonbases'>碱基吃柠檬</a>"

date: "`r Sys.Date()`"
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: true
always_allow_html: yes
---
# 说在前面的话

>你不再做你当初想做的事情，是因为停下脚步的理由最终战胜了继续前进的理由，因此，你要强化继续前进的理由，要么弱化停止脚步的理由。
> -- 安德斯•埃利克森 《刻意练习》


```bash
git 
```
## 关于本项目
在本项目中，我们将会由浅入深地介绍生物信息学及相关内容，内容将覆盖基本入门基础，以及现在热点领域所使用到的分析技巧等等。通过我们记录我们自己的项目分析，来分享生物信息学技术。
随着技术发展的日新月异，现在对单个细胞进行高通量测序(**scRNA-seq**)获得其全基因组的表达谱数据成为可能。**scRNA-seq**的主要优势是其单细胞水平的分辨率和基因组范围检测能力可以解决其他方法难以解决的问题，比如bulk RNA-seq和RT-qPCR。然而，为了分析scRNA-seq数据，需要新的方法，并且一些针对bulk RNA-seq实验开发的方法的潜在假设也不再适用。

在本课程中，我们将讨论使用scRNA-seq可以解决的一些问题以及可用的计算和统计方法。 本课程通过University of Cambridge的<a href="http://training.csx.cam.ac.uk/bioinformatics/" target="blank">Bioinformatics training unit</a>进行教学，但该页面的材料适用于任何有兴趣了解scRNA-seq数据计算分析的人。 本课程每年讲授两次，每次授课前材料都会更新。

计算工具的数量正在迅速增加，我们正在尽最大努力跟上最新进展。 本课程的主要限制之一是我们倾向使用在**R**中实现且运行速度相当快的工具。 此外，我们还承认某种程度上偏向于我们或我们的朋友和同事开发的方法。


## 许可

本课程所有资料均遵循**GPL-3**协议。 欢迎任何人浏览材料来学习。 如果您打算将这些材料用于您自己的教学，除了提供合适的引用外，如果您告诉我们，我们将不胜感激。

## 准备知识

在本书中，我们将会使用的到基本的linux, R, python等知识。但即使你是个初学者，你也不用因为没有任何基础而沮丧，跟随本课程提供入门训练(仅仅是入门训练)，你会掌握相应的技能来完成各个项目实战。当然，网络上会有很多比我们能够提供的更优秀的平台或者是材料，我们也会推荐给大家。

## 联系我们

如果您有任何的关于的意见，问题和建议,请直接在本repo下开issue进行说明.
